===================================================
Experiment Configuration:
- Hidden Dimension: 128
- Number of Heads: 8
- Number of Blocks: 6
- Patch Size: 16
- Learning Rate: 1e-4
- Start Time: Fri Dec 13 05:07:19 AM EST 2024
===================================================
Starting training for 7 epochs...

Epoch 1/7
Training:   0%|          | 0/781 [00:00<?, ?it/s]Training:   0%|          | 0/781 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/michel/repos/scratch_vit/train_cifar.py", line 295, in <module>
    vit_cifar.train_model()
  File "/home/michel/repos/scratch_vit/train_cifar.py", line 221, in train_model
    train_loss = self.train_iter()
  File "/home/michel/repos/scratch_vit/train_cifar.py", line 165, in train_iter
    self.model.backward(error)
  File "/home/michel/repos/scratch_vit/model/vit_finished.py", line 126, in backward
    error = block.backward(error)
  File "/home/michel/repos/scratch_vit/model/transformer_block.py", line 93, in backward
    grad_in = self.mha.backward(grad_in)
  File "/home/michel/repos/scratch_vit/model/multi_head_attention.py", line 97, in backward
    pre_attn_error = self.softmax[i].backward(err_attn)
  File "/home/michel/repos/scratch_vit/model/softmax.py", line 55, in backward
    softmax[..., cp.newaxis, :].transpose(
  File "cupy/_core/core.pyx", line 1295, in cupy._core.core._ndarray_base.__matmul__
  File "cupy/_core/_routines_linalg.pyx", line 960, in cupy._core._routines_linalg.matmul
  File "cupy/_core/core.pyx", line 137, in cupy._core.core.ndarray.__new__
  File "cupy/_core/core.pyx", line 225, in cupy._core.core._ndarray_base._init
  File "cupy/cuda/memory.pyx", line 738, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1424, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1445, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1116, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1137, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 1382, in cupy.cuda.memory.SingleDeviceMemoryPool._try_malloc
  File "cupy/cuda/memory.pyx", line 1385, in cupy.cuda.memory.SingleDeviceMemoryPool._try_malloc
cupy.cuda.memory.OutOfMemoryError: Out of memory allocating 8,690,991,616 bytes (allocated so far: 15,889,874,944 bytes).

real	0m1.719s
user	0m2.404s
sys	0m0.491s
